"""create_all_tables

Revision ID: c37943173b23
Revises: 
Create Date: 2026-03-14 15:07:56.721197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c37943173b23'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pacientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('idade', sa.Integer(), nullable=True),
    sa.Column('sexo', sa.String(length=1), nullable=True),
    sa.Column('altura_cm', sa.Float(), nullable=True),
    sa.Column('peso_kg', sa.Float(), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('tipo_bike', sa.String(length=50), nullable=True),
    sa.Column('experiencia', sa.String(length=50), nullable=True),
    sa.Column('km_semana', sa.Float(), nullable=True),
    sa.Column('objetivo', sa.String(length=50), nullable=True),
    sa.Column('lesoes', sa.Text(), nullable=True),
    sa.Column('dores', sa.Text(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pacientes_id'), 'pacientes', ['id'], unique=False)
    op.create_table('medidas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('entrepernas', sa.Float(), nullable=True),
    sa.Column('femur', sa.Float(), nullable=True),
    sa.Column('tibia', sa.Float(), nullable=True),
    sa.Column('braco', sa.Float(), nullable=True),
    sa.Column('antebraco', sa.Float(), nullable=True),
    sa.Column('tronco', sa.Float(), nullable=True),
    sa.Column('ombros_largura', sa.Float(), nullable=True),
    sa.Column('flexibilidade_isquiotibiais', sa.String(length=50), nullable=True),
    sa.Column('toque_dedos_chao', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medidas_id'), 'medidas', ['id'], unique=False)
    op.create_table('sessoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('angulos_antes', sa.JSON(), nullable=True),
    sa.Column('angulos_depois', sa.JSON(), nullable=True),
    sa.Column('ajustes', sa.JSON(), nullable=True),
    sa.Column('foto_antes_path', sa.String(length=500), nullable=True),
    sa.Column('foto_depois_path', sa.String(length=500), nullable=True),
    sa.Column('video_path', sa.String(length=500), nullable=True),
    sa.Column('relatorio_pdf_path', sa.String(length=500), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('finalizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessoes_id'), 'sessoes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessoes_id'), table_name='sessoes')
    op.drop_table('sessoes')
    op.drop_index(op.f('ix_medidas_id'), table_name='medidas')
    op.drop_table('medidas')
    op.drop_index(op.f('ix_pacientes_id'), table_name='pacientes')
    op.drop_table('pacientes')
    # ### end Alembic commands ###
